version: '3.6'
services:
  postgres:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: myuser
      POSTGRES_DB: mydb
    ports:
      - '5432:5432'
    volumes:
      - barley_hasura_postgres:/var/lib/postgresql/data

  hasura:
    image: hasura/graphql-engine:v2.26.0
    ports:
      - '8080:8080'
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://myuser:mysecretpassword@postgres:5432/mydb
      # HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:mysecretpassword@postgres-barley:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'true'
      HASURA_GRAPHQL_ADMIN_SECRET: myadminsecret
    depends_on:
      - postgres

volumes:
  barley_hasura_postgres:
