services:
  server:
    image: nest-barley-backend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    ports:
      - 3000:3000
    environment:
      - BUCKET_NAME=${BUCKET_NAME}
      - BUCKET_REGION=${BUCKET_REGION}
      - ACCESS_KEY=${ACCESS_KEY}
      - SECRET_ACCESS_KEY=${SECRET_ACCESS_KEY}
      - SECRET=${SECRET}
      - DB_HOST=postgres
    networks:
      - barley-network
    container_name: nest-barley-backend-container
    depends_on:
      - postgres
      - hasura

  postgres:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: myuser
      POSTGRES_DB: mydb
    ports:
      - '5432:5432'
    volumes:
      - barley_hasura_postgres:/var/lib/postgresql/data
    networks:
      - barley-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U myuser -d mydb']
      interval: 10s
      timeout: 5s
      retries: 5

  hasura:
    image: hasura/graphql-engine:v2.42.0
    ports:
      - '8080:8080'
    restart: always
    environment:
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://myuser:mysecretpassword@postgres:5432/mydb
      HASURA_GRAPHQL_DATABASE_URL: postgres://myuser:mysecretpassword@postgres:5432/mydb
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'true'
      HASURA_GRAPHQL_ADMIN_SECRET: myadminsecret
      ACTION_BASE_URL: http://server:3000
    networks:
      - barley-network
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  barley_hasura_postgres:

networks:
  barley-network:
    driver: bridge
